sudo: false
language: ruby
bundler_args: --without development
rvm:
  - 2
  - 2.0
  - 2.1
  - 2.1.10
  - 2.2
  - ruby-head
  - ruby-head-clang
  - jruby-head
matrix:
  fast_finish: true
  allow_failures:
    - rvm: jruby-head
    - rvm: ruby-head
    - rvm: ruby-head-clang
    - rvm: 2.1.10
script:
  - bundle exec rspec
notifications:
  webhooks:
    - http://buildtimetrend.herokuapp.com/travis # trigger Buildtime Trend Service to parse Travis CI log
