AllCops:
  DisplayCopNames: true
  Exclude:
    - 'spec/fixtures'

Metrics/LineLength:
  Max: 120

Style/SpaceAroundEqualsInParameterDefault:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes
